version: "3.8"

services:
  postgres:
    image: postgres
    container_name: mernpg-container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - mernpgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  mernpgdata:
    name: mernpgdata
